server:
  port: 9092
spring:  
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    password: '12345678'
    platform: mysql
    url: jdbc:mysql://db4free.net:3306/usersapi
    username: vinigomes
    hikari:
        maximum-pool-size: 30
        connectionTimeout: 30000
        idleTimeout: 600000
        maxLifetime: 1800000
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9091/auth/user
messages:
  parseUtilsError: There was an error while trying to get a new instance of class to parse request. Cause {} Message {}
  emailSucessChanged: Email was changed successfully
  emailAlreadyRegistered: Email %s already registered 
  loginAlreadyRegistered: Login %s already registered
